version: "3"
services:
    nginx:
        container_name: "nginx"
        image: "nginx"
        ports:
            - "443:443"
        env_file:
            - .env
        volumes:
            - ./requirements/wordpress/srcs/www:/var/www
        networks:
            - inception
        restart: always
    wordpress:
        container_name: "wordpress"
        image: "wordpress"
        env_file:
            - .env
        volumes:
            - ./requirements/wordpress/srcs/www:/var/www
        networks:
            - inception
        restart: always
    mariadb:
        container_name: "mariadb"
        image: "mariadb"
        env_file:
            - .env
        # volumes:
        #     - ./requirements/mariadb/srcs/database:/var/lib/mysql
        networks:
            - inception
        restart: always
<<<<<<< HEAD
        #ftp:
        #container_name: "ftp"
        #image: "ftp"
=======
    ftp:
        container_name: "ftp"
        image: "ftp"
		ports:
			- "21:21"
			- "30000-30100:30000-30100"
>>>>>>> 267daf393b336ba5ca0133a40514253a069eccae
        # volumes:
        #     - 
        #networks:
        #   - inception
        #restart: always

networks:
    inception:
        name: "inception"
