version: "3"
services:
    nginx:
        container_name: "nginx"
        image: "nginx"
        ports:
            - "443:443"
        env_file:
            - .env
        networks:
            - inception
        restart: always
    wordpress:
        container_name: "wordpress"
        image: "wordpress"
        env_file:
            - .env
        networks:
            - inception
        restart: always
    mariadb:
        container_name: "mariadb"
        image: "mariadb"
        env_file:
            - .env
        networks:
            - inception
        restart: always

networks:
    inception:
        name: "inception"