version: "3"
services:
    nginx:
        container_name: "nginx"
        image: nginx
        ports:
            - "443:443"
        env_file:
            - .env
        volumes:
            - site-files:/var/www
        networks:
            - inception
        restart: always
    wordpress:
        container_name: "wordpress"
        image: wordpress
        env_file:
            - .env
        volumes:
            - site-files:/var/www
        networks:
            - inception
        restart: always
    mariadb:
        container_name: "mariadb"
        image: mariadb
        env_file:
            - .env
        volumes:
            - database:/var/lib/mysql
        networks:
            - inception
        restart: always
    ftp:
        container_name: "ftp"
        image: ftp
        ports:
            - "21:21"
            - "30000:30000"
        volumes:
            - site-files:/home/iounejja
        networks:
            - inception
        restart: always
    redis:
        container_name: redis
        image: redis
        networks:
            - inception
        restart: always
    adminer:
        container_name: adminer
        image: adminer
        volumes:
            - site-files:/var/www
        networks:
            - inception
        restart: always
    grafana:
        container_name: grafana
        image: grafana
        ports:
            - "3000:3000"
        networks:
            - inception
        restart: always
    influxdb:
        container_name: influxdb
        image: influxdb
        volumes:
            - influxdb:/var/lib/influxdb/data/collectd
        networks:
            - inception
        restart: always

volumes:
    site-files:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/iounejja/data/site-files'
    database:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/iounejja/data/database'
    influxdb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/iounejja/data/influxdb'

networks:
    inception:
        name: "inception"
